//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 108")]
        public global::System.Drawing.Point CooldownsPosition {
            get {
                return ((global::System.Drawing.Point)(this["CooldownsPosition"]));
            }
            set {
                this["CooldownsPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 255, 0")]
        public global::System.Drawing.Color CooldownsColors {
            get {
                return ((global::System.Drawing.Color)(this["CooldownsColors"]));
            }
            set {
                this["CooldownsColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 24pt")]
        public global::System.Drawing.Font CooldownsFont {
            get {
                return ((global::System.Drawing.Font)(this["CooldownsFont"]));
            }
            set {
                this["CooldownsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Divide")]
        public string TopFirstSpellHotkey {
            get {
                return ((string)(this["TopFirstSpellHotkey"]));
            }
            set {
                this["TopFirstSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Multiply")]
        public string TopSecondSpellHotkey {
            get {
                return ((string)(this["TopSecondSpellHotkey"]));
            }
            set {
                this["TopSecondSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad8")]
        public string JungleFirstSpellHotkey {
            get {
                return ((string)(this["JungleFirstSpellHotkey"]));
            }
            set {
                this["JungleFirstSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad9")]
        public string JungleSecondSpellHotkey {
            get {
                return ((string)(this["JungleSecondSpellHotkey"]));
            }
            set {
                this["JungleSecondSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad5")]
        public string MidFirstSpellHotkey {
            get {
                return ((string)(this["MidFirstSpellHotkey"]));
            }
            set {
                this["MidFirstSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad6")]
        public string MidSecondSpellHotkey {
            get {
                return ((string)(this["MidSecondSpellHotkey"]));
            }
            set {
                this["MidSecondSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad2")]
        public string AdcFirstSpellHotkey {
            get {
                return ((string)(this["AdcFirstSpellHotkey"]));
            }
            set {
                this["AdcFirstSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad3")]
        public string AdcSecondSpellHotkey {
            get {
                return ((string)(this["AdcSecondSpellHotkey"]));
            }
            set {
                this["AdcSecondSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+NumPad0")]
        public string SupportFirstSpellHotkey {
            get {
                return ((string)(this["SupportFirstSpellHotkey"]));
            }
            set {
                this["SupportFirstSpellHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ctrl+Decimal")]
        public string SupportSecondSpellHotkey {
            get {
                return ((string)(this["SupportSecondSpellHotkey"]));
            }
            set {
                this["SupportSecondSpellHotkey"] = value;
            }
        }
    }
}
